name: Deployment
on: [push]
jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image for Project 1
        uses: docker/build-push-action@v2
        with:
          context: ./backend-application  # Set the context to the Project 1 directory
          push: true
          tags: clipbook/demo-backend-app:latest
