name: Deployment
on: [push]
jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v2
        with:
          path: |
            /root/.docker
            ./backend-application # Replace with the path to your Dockerfile
          key: docker-layers-${{ hashFiles('./backend-application) }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image for Project 1
        uses: docker/build-push-action@v2
        with:
          context: ./backend-application  # Set the context to the Project 1 directory
          push: true
          tags: clipbook/demo-backend-app:latest



  gke-connect:
    needs: [backend-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache gcloud components
        uses: actions/cache@v2
        with:
          path: ~/.config/gcloud/components
          key: gcloud-components-{{ runner.os }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY_BASE64 }}
          project_id: ambient-stack-376816 # Replace 'my-project' with your actual GCP project ID

      - name: Authenticate with GKE Cluster
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials autopilot-cluster-1 --region asia-south2 --project ambient-stack-376816
          kubectl apply -f ./kubernetes/backend-deployment.yaml